package com.IMM2020.imm_project;


public class Question {

    public String[] questions = {

            "Addition of motor units to increase the force of contraction in muscles is called what?",
            "An EMG Signal is:",
            "Consists of a motor neuron and all the skeletal muscle fibers with which it synapses is:",
            "Nerve cells that Transmit information to muscles are called what?",
            "The Conduction velocity of motor nerves is approximately:"
    };

    public String[][] choices = {
            {"Recruitment",
                    "Extensor",
                    "Muscle twitch",
                    "Flexing"},
            {"1.Summation of all electrical potentials generated by excitable cells X",
                    "2.Summation of all neuro Contractions of muscles ",
                    "3.The inability of muscle to continue to generate or sustain tension",
                    "4.The electric pulse moving through the nerves.",
            },
            {"EMG Signal",
                    "Motor Unit",
                    "Recruitment",
                    "Sarcomere"},
            {"Sensory neurons",
                    "Motor neurons",
                    "Interneurons",
                    "Chemical neurons"},
            {"10m/s",
                    "2m/s",
                    "50m/s",
                    "15m/s"}
    };

    public String[] correctAnswer = {
            "Recruitment",
            "1.Summation of all electrical potentials generated by excitable cells",
            "Motor Unit",
            "Motor neurons",
            "50m/s"};


    public String getQuestion(int a) {
        String question = questions[a];
        return question;
    }

    public String getchoice1(int a) {
        String choice = choices[a][0];
        return choice;
    }

    public String getchoice2(int a){
        String choice = choices[a][1];
        return choice;
    }

    public String getchoice3(int a){
        String choice = choices[a][2];
        return choice;
    }

    public String getchoice4(int a){
        String choice = choices[a][3];
        return choice;
    }

    public String getCorrectAnswer(int a){
        String answer = correctAnswer[a];
        return answer;
    }
}
