package com.IMM2020.imm_project;

public class Question {
    public String questions[] = {
            "Which is a Programming Language?",
            "In COMAL language program, after name of procedure parameters must be in?",
            "Programming language COBOL works best for use in?"
    };

    public String[][] choices = {
            {"Recruitment",
                    "Extensor",
                    "Muscle twitch",
                    "empty"},
            {"1.Summation of all electrical potentials generated by excitable cells X",
                    "2.Summation of all neuro Contractions of muscles ",
                    "3.The inability of muscle to continue to generate or sustain tension",
                    "empty",
            },
            {"EMG Signal",
                    "Motor Unit",
                    "Recruitment",
                    "empty"},
            {"Sensory neurons",
                    "Motor neurons",
                    "Interneurons",
                    "Chemical neurons"},
            {"10m/s",
                    "2m/s",
                    "50m/s",
                    "15m/s"}
    };

    public String[] correctAnswer = {
            "Recruitment",
            "1.Summation of all electrical potentials generated by excitable cells",
            "Motor Unit",
            "Motor neurons",
            "50m/s"};


    public String getQuestion(int a) {
        String question = questions[a];
        return question;
    }

    public String getchoice1(int a) {
        String choice = choices[a][0];
        return choice;
    }

    public String getchoice2(int a){
        String choice = choices[a][1];
        return choice;
    }

    public String getchoice3(int a){
        String choice = choices[a][2];
        return choice;
    }

    public String getchoice4(int a){
        String choice = choices[a][3];
        return choice;
    }

    public String getCorrectAnswer(int a){
        String answer = correctAnswer[a];
        return answer;
    }
}
